In [1]:
## Loading the Data

In [2]:
import pyreadstat

ch, metadata = pyreadstat.read_sav("ch.sav")

In [3]:
ch.shape

(29335, 154)

In [4]:
## Creating Working Dataset

In [5]:
analysis = ch.copy()

In [6]:
## Keep Needed Variables

In [7]:
variables = [
    'IM16',
    'windex5',
    'melevel',
    'Zone',
    'HL4',
    'CAGE',
    'chweight'
]

analysis = analysis[variables].copy()

In [8]:
analysis.shape

(29335, 7)

In [9]:
analysis.head()

   IM16  windex5  melevel  Zone  HL4  CAGE  chweight
0   NaN      5.0      3.0   4.0  1.0  33.0  0.645488
1   NaN      5.0      3.0   4.0  2.0  14.0  0.645488
2   NaN      5.0      3.0   4.0  2.0  52.0  0.645488
3   NaN      5.0      3.0   4.0  2.0  58.0  0.645488
4   1.0      5.0      3.0   4.0  2.0  34.0  0.645488

In [10]:
## Understand the Outcome Variable

In [11]:
analysis['IM16'].value_counts(dropna=False)

IM16
NaN    23797
1.0     3250
2.0     2105
8.0      167
9.0       16
Name: count, dtype: int64

In [12]:
metadata.variable_value_labels.get('IM16')

{1.0: 'Yes', 2.0: 'No', 8.0: 'DK', 9.0: 'Missing'}

In [13]:
analysis['windex5'].value_counts(dropna=False)

windex5
1.0    6460
2.0    6355
3.0    5595
4.0    5367
5.0    5065
0.0     493
Name: count, dtype: int64

In [14]:
metadata.variable_value_labels.get('windex5')

{1.0: 'Poorest', 2.0: 'Second', 3.0: 'Middle', 4.0: 'Fourth', 5.0: 'Richest'}

In [15]:
analysis['melevel'].value_counts(dropna=False)

melevel
3.0    8507
1.0    7951
5.0    5583
2.0    4906
4.0    2384
9.0       4
Name: count, dtype: int64

In [16]:
metadata.variable_value_labels.get('melevel')

{1.0: 'None',
 2.0: 'Primary',
 3.0: 'Secondary / Secondary-technical',
 4.0: 'Higher',
 5.0: 'Non-formal',
 9.0: 'Missing/DK'}

In [17]:
analysis['Zone'].value_counts(dropna=False)

Zone
3.0    9662
1.0    5696
2.0    4855
5.0    3395
6.0    3196
4.0    2531
Name: count, dtype: int64

In [18]:
metadata.variable_value_labels.get('Zone')

{1.0: 'North central',
 2.0: 'North east',
 3.0: 'North west',
 4.0: 'South east',
 5.0: 'South south',
 6.0: 'South west'}

In [19]:
analysis['HL4'].value_counts(dropna=False)

HL4
1.0    14845
2.0    14490
Name: count, dtype: int64

In [20]:
metadata.variable_value_labels.get('HL4')

{1.0: 'Male', 2.0: 'Female', 9.0: 'Missing'}

In [21]:
analysis['CAGE'].describe()

count    28842.000000
mean        29.315685
std         17.106398
min          0.000000
25%         14.000000
50%         29.000000
75%         44.000000
max         59.000000
Name: CAGE, dtype: float64

In [22]:
## Getting a Baseline

In [23]:
analysis.shape

(29335, 7)

In [24]:
analysis.isna().sum()

IM16        23797
windex5         0
melevel         0
Zone            0
HL4             0
CAGE          493
chweight        0
dtype: int64

In [25]:
analysis['IM16'].value_counts(dropna=False)

IM16
NaN    23797
1.0     3250
2.0     2105
8.0      167
9.0       16
Name: count, dtype: int64

In [26]:
analysis.groupby('CAGE')['IM16'].value_counts(dropna=False)

CAGE  IM16
0.0   NaN     221
      2.0      18
      1.0       2
1.0   NaN     459
      2.0      60
             ...
55.0  NaN     501
56.0  NaN     450
57.0  NaN     395
58.0  NaN     379
59.0  NaN     341
Name: count, Length: 181, dtype: int64

In [27]:
analysis.groupby('CAGE')['IM16'].value_counts()

CAGE  IM16
0.0   2.0     18
      1.0      2
1.0   2.0     60
      1.0      9
      9.0      2
              ..
35.0  8.0      4
36.0  1.0     24
      2.0      8
      8.0      1
      9.0      1
Name: count, Length: 121, dtype: int64

In [28]:
## Creating new Dataframe

In [29]:
measles = analysis[analysis['IM16'].notna()].copy()

In [30]:
measles.shape

(5538, 7)

In [31]:
measles['CAGE'].describe()

count    5538.000000
mean       20.403034
std         9.378987
min         0.000000
25%        14.000000
50%        21.000000
75%        28.000000
max        36.000000
Name: CAGE, dtype: float64

In [32]:
measles['CAGE'].value_counts().sort_index()

CAGE
0.0      20
1.0      72
2.0      65
3.0      98
4.0     106
5.0      99
6.0     103
7.0      88
8.0     114
9.0     105
10.0     94
11.0     81
12.0    161
13.0    168
14.0    206
15.0    164
16.0    197
17.0    192
18.0    180
19.0    195
20.0    181
21.0    156
22.0    157
23.0    171
24.0    192
25.0    211
26.0    183
27.0    201
28.0    216
29.0    217
30.0    206
31.0    196
32.0    194
33.0    205
34.0    161
35.0    149
36.0     34
Name: count, dtype: int64

In [33]:
## Understanding Missing and Unknown Values

In [34]:
measles.groupby('IM16')['CAGE'].describe()

       count       mean        std  min    25%   50%   75%   max
IM16
1.0   3250.0  22.975077   7.904691  0.0  17.00  24.0  30.0  36.0
2.0   2105.0  16.371971  10.082119  0.0   7.00  16.0  26.0  36.0
8.0    167.0  21.502994   8.518495  1.0  15.00  22.0  28.0  36.0
9.0     16.0  16.812500  11.617336  1.0   5.75  17.0  25.5  36.0

In [35]:
measles.groupby('IM16')['windex5'].value_counts().sort_index()

IM16  windex5
1.0   1.0        355
      2.0        543
      3.0        666
      4.0        822
      5.0        864
2.0   1.0        603
      2.0        533
      3.0        363
      4.0        341
      5.0        265
8.0   1.0         27
      2.0         39
      3.0         45
      4.0         35
      5.0         21
9.0   1.0          2
      2.0          7
      3.0          5
      5.0          2
Name: count, dtype: int64

In [36]:
## Identifying the specific population useful for analysis

In [37]:
metadata.variable_value_labels.get('source')

{1.0: 'Core (MICS) EAs', 2.0: 'Supplemental EAs'}

In [38]:
analysis['IM16'].value_counts(dropna=False)

IM16
NaN    23797
1.0     3250
2.0     2105
8.0      167
9.0       16
Name: count, dtype: int64

In [39]:
analysis['source'] = ch['source']

In [40]:
analysis.shape

(29335, 8)

In [41]:
metadata.variable_value_labels.get('source')

{1.0: 'Core (MICS) EAs', 2.0: 'Supplemental EAs'}

In [42]:
analysis['source'].value_counts(dropna=False)

source
1.0    28578
2.0      757
Name: count, dtype: int64

In [43]:
## Identifying correlation between population variables needed for analysis

In [44]:
import pandas as pd

In [45]:
pd.crosstab(
    analysis['source'],
    analysis['IM16'],
    dropna=False
)

IM16     1.0   2.0  8.0  9.0    NaN
source
1.0     3013  2048  146   14  23357
2.0      237    57   21    2    440

In [46]:
analysis.groupby('source')['CAGE'].describe()

          count       mean        std   min   25%   50%   75%   max
source
1.0     28085.0  29.640627  17.210403   0.0  14.0  30.0  44.0  59.0
2.0       757.0  17.260238   3.313779  12.0  15.0  17.0  20.0  24.0

In [47]:
## Understanding the population

In [48]:
analysis['IM16_present'] = analysis['IM16'].notna()

In [49]:
pd.crosstab(
    analysis['CAGE'],
    analysis['IM16_present']
)

IM16_present  False  True
CAGE
0.0             221     20
1.0             459     72
2.0             387     65
3.0             400     98
4.0             439    106
5.0             382     99
6.0             385    103
7.0             393     88
8.0             393    114
9.0             365    105
10.0            302     94
11.0            274     81
12.0            425    161
13.0            407    168
14.0            410    206
15.0            355    164
16.0            398    197
17.0            384    192
18.0            369    180
19.0            360    195
20.0            283    181
21.0            277    156
22.0            252    157
23.0            220    171
24.0            255    192
25.0            283    211
26.0            301    183
27.0            288    201
28.0            287    216
29.0            315    217
30.0            320    206
31.0            276    196
32.0            232    194
33.0            229    205
34.0            192    161
35.0            172    149
36.0            426     34
37.0            517      0
38.0            501      0
39.0            562      0
40.0            548      0
41.0            610      0
42.0            604      0
43.0            532      0
44.0            484      0
45.0            396      0
46.0            360      0
47.0            351      0
48.0            439      0
49.0            481      0
50.0            496      0
51.0            526      0
52.0            558      0
53.0            560      0
54.0            597      0
55.0            501      0
56.0            450      0
57.0            395      0
58.0            379      0
59.0            341      0

In [50]:
nics = analysis[
    (analysis['CAGE'] >= 12) &
    (analysis['CAGE'] <= 23)
].copy()

nics.shape

(6268, 9)

In [51]:
## Cleaning variable outcomes

In [52]:
## Cleaning IM16

In [53]:
nics['IM16'].value_counts(dropna=False)

IM16
NaN    4140
1.0    1380
2.0     678
8.0      66
9.0       4
Name: count, dtype: int64

In [54]:
nics['IM16'].isna().sum()

np.int64(4140)

In [55]:
## Defining the population in NICS sample

In [56]:
nics = analysis[analysis["CAGE"].between(12, 23)].copy()

print(nics.shape)
print(nics["source"].value_counts(dropna=False))

pd.crosstab(
    nics["source"],
    nics["IM16"],
    dropna=False
)

(6268, 9)
source
1.0    5522
2.0     746
Name: count, dtype: int64

IM16     1.0  2.0  8.0  9.0   NaN
source
1.0     1149  621   45    2  3705
2.0      231   57   21    2   435

In [57]:
ch.groupby('source')['CAGE'].describe()

          count       mean        std   min   25%   50%   75%   max
source
1.0     28085.0  29.640627  17.210403   0.0  14.0  30.0  44.0  59.0
2.0       757.0  17.260238   3.313779  12.0  15.0  17.0  20.0  24.0

In [58]:
## Verify Analytical Dataset
# The dataset (nics) contains 6,268 children aged 12–23 months and consists of 5,522 core MICS records and 746 supplemental NICS records.

In [59]:
nics.shape

(6268, 9)

In [60]:
# Variables required for the analysis
analysis_vars = [
    "IM16",
    "windex5",
    "melevel",
    "Zone",
    "HL4",
    "CAGE",
    "chweight",
    "source"
]

nics[analysis_vars].info()

<class 'pandas.core.frame.DataFrame'>
Index: 6268 entries, 1 to 29334
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   IM16      2128 non-null   float64
 1   windex5   6268 non-null   float64
 2   melevel   6268 non-null   float64
 3   Zone      6268 non-null   float64
 4   HL4       6268 non-null   float64
 5   CAGE      6268 non-null   float64
 6   chweight  6268 non-null   float64
 7   source    6268 non-null   float64
dtypes: float64(8)
memory usage: 440.7 KB

In [61]:
# Preview the analytical variables
nics[analysis_vars].head()

    IM16  windex5  melevel  Zone  HL4  CAGE  chweight  source
1    NaN      5.0      3.0   4.0  2.0  14.0  0.645488     1.0
9    1.0      5.0      3.0   4.0  1.0  21.0  0.645488     1.0
22   1.0      4.0      1.0   4.0  2.0  15.0  0.364121     1.0
26   1.0      5.0      3.0   4.0  1.0  18.0  0.364121     1.0
29   1.0      5.0      3.0   4.0  1.0  14.0  0.314469     1.0

In [62]:
## Verify age restriction

In [63]:
nics["CAGE"].describe()

count    6268.000000
mean       17.073867
std         3.346983
min        12.000000
25%        14.000000
50%        17.000000
75%        20.000000
max        23.000000
Name: CAGE, dtype: float64

In [64]:
## Check for duplicates

In [65]:
nics.duplicated().sum()

np.int64(144)

In [66]:
# Check duplicate rows within each source
nics.groupby("source", group_keys=False).apply(
    lambda x: x.duplicated().sum(),
    include_groups=False
)

source
1.0    131
2.0     13
dtype: int64

In [67]:
# View some of the duplicated rows
# Duplicate check: 144 rows were identified as identical across the selected analytical variables. Because the reduced analytical dataset does not contain a unique child identifier, these cannot be assumed to represent duplicate children. The rows are therefore retained.

In [68]:
nics[nics.duplicated(keep=False)].sort_values(
    by=["source", "CAGE", "IM16"]
).head(20)

       IM16  windex5  melevel  Zone  HL4  CAGE  chweight  source  IM16_present
7158    1.0      5.0      3.0   5.0  1.0  12.0  1.951365     1.0          True
7159    1.0      5.0      3.0   5.0  1.0  12.0  1.951365     1.0          True
7167    1.0      5.0      3.0   5.0  1.0  12.0  1.951365     1.0          True
15358   2.0      1.0      1.0   3.0  2.0  12.0  0.788472     1.0          True
15371   2.0      1.0      1.0   3.0  2.0  12.0  0.788472     1.0          True
5840    NaN      3.0      3.0   5.0  1.0  12.0  0.618422     1.0         False
6229    NaN      3.0      3.0   5.0  1.0  12.0  0.618422     1.0         False
8259    NaN      1.0      1.0   2.0  1.0  12.0  0.544155     1.0         False
8271    NaN      1.0      1.0   2.0  1.0  12.0  0.544155     1.0         False
11910   NaN      2.0      5.0   3.0  1.0  12.0  0.416278     1.0         False
12748   NaN      3.0      5.0   3.0  1.0  12.0  0.514225     1.0         False
12750   NaN      3.0      5.0   3.0  1.0  12.0  0.514225     1.0         False
13088   NaN      1.0      5.0   3.0  2.0  12.0  0.204058     1.0         False
13091   NaN      1.0      5.0   3.0  2.0  12.0  0.204058     1.0         False
13101   NaN      2.0      5.0   3.0  2.0  12.0  0.244869     1.0         False
13112   NaN      2.0      5.0   3.0  2.0  12.0  0.244869     1.0         False
13546   NaN      1.0      5.0   3.0  2.0  12.0  0.277519     1.0         False
13548   NaN      1.0      5.0   3.0  2.0  12.0  0.277519     1.0         False
13640   NaN      2.0      5.0   3.0  1.0  12.0  0.416278     1.0         False
13708   NaN      2.0      5.0   3.0  2.0  12.0  0.432335     1.0         False

In [69]:
## Inspect IM16: Measles Vaccination

In [70]:
nics["IM16"].value_counts(dropna=False).sort_index()

IM16
1.0    1380
2.0     678
8.0      66
9.0       4
NaN    4140
Name: count, dtype: int64

In [71]:
# IM16 distribution by data source
nics.groupby("source")["IM16"].value_counts(dropna=False).sort_index()

source  IM16
1.0     1.0     1149
        2.0      621
        8.0       45
        9.0        2
        NaN     3705
2.0     1.0      231
        2.0       57
        8.0       21
        9.0        2
        NaN      435
Name: count, dtype: int64

In [72]:
# Check IM16 presence indicator
nics["IM16_present"].value_counts(dropna=False)

IM16_present
False    4140
True     2128
Name: count, dtype: int64

In [73]:
## Create clean measles vaccination outcome

In [74]:
nics["measles_vaccinated"] = nics["IM16"].map({
    1.0: 1,
    2.0: 0
})

In [75]:
nics["measles_vaccinated"].value_counts(dropna=False)

measles_vaccinated
NaN    4210
1.0    1380
0.0     678
Name: count, dtype: int64

In [76]:
nics.groupby("source")["measles_vaccinated"].value_counts(
    dropna=False
).sort_index()

source  measles_vaccinated
1.0     0.0                    621
        1.0                   1149
        NaN                   3752
2.0     0.0                     57
        1.0                    231
        NaN                    458
Name: count, dtype: int64

In [77]:
## IM16 Availability

In [78]:
im16_availability = (
    nics.groupby("source")["measles_vaccinated"]
    .agg(
        valid="count",
        total="size"
    )
)

im16_availability["missing"] = (
    im16_availability["total"] - im16_availability["valid"]
)

im16_availability["valid_percent"] = (
    im16_availability["valid"] /
    im16_availability["total"] * 100
)

im16_availability

        valid  total  missing  valid_percent
source
1.0      1770   5522     3752      32.053604
2.0       288    746      458      38.605898

In [79]:
im16_availability = (
    nics.groupby("source")["measles_vaccinated"]
    .agg(
        valid="count",
        total="size"
    )
)

im16_availability["missing"] = (
    im16_availability["total"] - im16_availability["valid"]
)

im16_availability["valid_percent"] = (
    im16_availability["valid"] /
    im16_availability["total"] * 100
)

im16_availability

        valid  total  missing  valid_percent
source
1.0      1770   5522     3752      32.053604
2.0       288    746      458      38.605898

In [80]:
# IM16 Availability by age

In [81]:
nics.groupby("CAGE")["measles_vaccinated"].agg(
    valid="count",
    total="size"
).assign(
    valid_percent=lambda x: x["valid"] / x["total"] * 100
)

      valid  total  valid_percent
CAGE
12.0    159    586      27.133106
13.0    160    575      27.826087
14.0    200    616      32.467532
15.0    158    519      30.443160
16.0    190    595      31.932773
17.0    184    576      31.944444
18.0    174    549      31.693989
19.0    190    555      34.234234
20.0    177    464      38.146552
21.0    150    433      34.642032
22.0    149    409      36.430318
23.0    167    391      42.710997

In [ ]:
## IM16 Availability

#IM16 was available for 2,058 of the 6,268 children in the analytical dataset (32.8%). 
#Availability was 32.1% among core MICS records and 38.6% among supplemental NICS records.

#Records with missing IM16 were also found to have missing values for other immunisation 
#variables (IM7, IM8, and IM15A). Therefore, missing IM16 values were not interpreted as 
#measles-specific nonresponse and were not recoded as unvaccinated.

#For analyses of measles vaccination status, children with valid IM16 responses 
#(IM16 = 1 or 2) will form the outcome-specific analytical denominator. IM16 codes 8 
#and 9 are treated as indeterminate.

In [83]:
nics.shape

(6268, 10)